const courses=[
{title:'Media Literacy, Fake News and Critical Thinking',short:'Fake news, krytyczne myślenie i odporność na manipulację',goals:['To develop the ability to recognise and counteract fake news and misinformation','To strengthen participants’ resilience to manipulation and biased information','To enhance critical thinking and analytical decision-making skills','To reduce stress and anxiety linked to information overload','To promote democratic values, media responsibility, and EU principles'],days:[
['Poniedziałek','13:45-19:30',['Welcoming everyone in Kalamata - Introduction to the course','13:45-14:00 Meeting each other in the Flisvos Hotel lobby','14:00-16:00 Introduction to the course and getting to know each other','Introduction to Areadne LLC & Erasmus+ opportunities','16:00-19:30 Introduction to Media Literacy','Media literacy and information ecosystems','Types of misinformation and disinformation','Principles of Adult Learning','Motivation & Engagement in Adult Education']],
['Wtorek','14:00-19:30',['Fake News, Manipulation, and Bias','Recognising fake news and manipulated content','Emotional triggers and cognitive biases','Fact-checking tools and verification techniques','Practical workshop: Analysing real news examples','Critical Thinking and Decision-Making','Critical information analysis skills','Evaluating sources, data, and narratives','Making informed life, health, and professional decisions','Case studies: Health misinformation and risk communication']],
['Środa','14:00-19:30',['Socially Sensitive Topics and Media Impact','Media narratives on politics, migration, refugees, and war','EU values, democratic principles, and responsible communication','Ethical dilemmas in information sharing','Group work: Deconstructing media narratives']],
['Czwartek','09:00-14:30',['Resilience, Well-Being, and Democratic Engagement','Increasing resistance to fact manipulation','Managing stress and anxiety caused by negative information overload','Building healthy media consumption habits']],
['Piątek','14:00-19:30',['Facilitation, Evaluation & Final Project','Facilitation Techniques','Managing Learner Engagement','Evaluation & Impact Measurement','Challenges & Ethics','Future Trends in literacy and multiliteracies','Certificate ceremony']]
]},
{title:'Effective Communication & Public Speaking',short:'Komunikacja, wystąpienia publiczne i prezentacje',goals:['To develop confidence and clarity in public speaking','To improve the quality and effectiveness of educational communication','To enhance audience engagement and interaction','To strengthen assertiveness, emotional intelligence, and leadership skills','To support reflective practice and self-awareness in communication'],days:[
['Poniedziałek','13:45-19:30',['Welcoming everyone in Kalamata - Introduction to the course','13:45-14:00 Meeting each other in Flisvos Hotel','14:00-17:00 Introduction to the course and getting to know each other','Introduction to Areadne LLC & Erasmus+ opportunities','17:00-19:30 Foundations of Effective Communication','Communication in adult education contexts','Introduction to soft skills and key competencies','Self-assessment of communication styles','Practical exercise: Communication strengths and challenges']],
['Wtorek','14:00-19:30',['Public Speaking Essentials','Basic elements of public speaking','Voice, articulation, and structure','Overcoming stage fright and building confidence','Individual practice: Short speeches with feedback','Planning and Delivering Impactful Presentations','Planning a public speech or educational presentation','Structuring content for adult learners','Storytelling techniques in education','Group activity: Designing and presenting a short talk']],
['Środa','14:00-19:30',['Non-Verbal Communication and Audience Engagement','Body language, posture, gestures, and eye contact','Reading the audience and active listening','Techniques for audience engagement and interaction','Practical workshop: Non-verbal communication exercises']],
['Czwartek','09:00-14:30',['Assertiveness, Emotional Intelligence, and Leadership','Assertiveness as a key communication skill','Emotional intelligence in adult education','Conflict management and constructive feedback','Final presentations, reflection, and action planning']],
['Piątek','14:00-19:30',['Facilitation, Evaluation & Final Project','Facilitation Techniques','Managing Learner Engagement','Evaluation & Impact Measurement','Challenges & Ethics','Certificates ceremony']]
]},
{title:'Gamification & Game-Based Learning',short:'Gamifikacja i projektowanie aktywności edukacyjnych',goals:['To introduce participants to the pedagogical foundations of games in 21st-century adult education','To distinguish clearly between gamification and game-based learning','To support reflection on participants’ current teaching practices and adult learning styles','To develop hands-on skills in designing gamified learning activities','To foster key competencies such as analytical thinking, creativity, digital skills, and collaboration'],days:[
['Poniedziałek','13:45-19:30',['Welcoming everyone in Kalamata - Introduction to the course','13:45-14:00 Meeting each other in the Flisvos Hotel','14:00-17:00 Introduction to the course','Getting to know each other','Introduction to Areadne LLC & Erasmus+ opportunities','17:00-19:30 Introduction to Gamification & Adult Learning','What is Gamification','Gamification vs Game-Based Learning','Principles of Adult Learning','Motivation & Engagement in Adult Education','Psychology of Motivation and Human Behavior']],
['Wtorek','14:00-19:30',['Mechanics, Dynamics & Player Experience','Game Mechanics: points, badges, levels, rewards, leaderboards','Player Types & Learner Personas','Storytelling & Narrative Learning','Challenge & Feedback Systems']],
['Środa','14:00-19:30',['Instructional Design & Gamified Learning Design','Learning Objectives & Gamified Outcomes','ADDIE Model & Gamification','Designing Assessment Through Games','Feedback Loops & Progression Systems','Inclusivity & Accessibility in Game-Based Learning']],
['Czwartek','09:00-14:30',['Game-Based Learning Strategies & Digital Tools','Serious Games','Educational Escape Rooms','Simulation Activities','Collaborative & Competitive Learning','Digital Game-Based Platforms']],
['Piątek','14:00-19:30',['Facilitation, Evaluation & Final Project','Facilitation Techniques','Managing Learner Engagement','Evaluation & Impact Measurement','Challenges & Ethics','Future Trends in Gamification','Certificate ceremony']]
]}
];
const courseList=document.getElementById('courseList');
const renderDays=(days,openFirst=false)=>days.map((d,idx)=>`<details class="day" ${openFirst&&idx===0?'open':''}><summary><span>${d[0]}</span><time>${d[1]}</time></summary><ul>${d[2].map(x=>`<li>${x}</li>`).join('')}</ul></details>`).join('');
courseList.innerHTML=courses.map((c,i)=>`<article class="course-card ${i===0?'open':''}"><button class="course-button" type="button"><span><h3>${c.title}</h3><p>${c.short}</p></span><span class="chev">⌄</span></button><div class="course-content"><div class="goals"><h4>Main Objectives</h4><ul>${c.goals.map(g=>`<li>${g}</li>`).join('')}</ul></div><div class="days"><h4>Course schedule</h4>${renderDays(c.days,true)}</div></div></article>`).join('');
document.getElementById('commonSchedule').innerHTML='';
document.querySelectorAll('.course-button').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.course-card');document.querySelectorAll('.course-card').forEach(c=>{if(c!==card)c.classList.remove('open')});card.classList.toggle('open')}));
let deferredPrompt;const installBtn=document.getElementById('installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;installBtn.hidden=true;deferredPrompt=null});if('serviceWorker'in navigator){navigator.serviceWorker.register('service-worker.js').then(()=>{document.getElementById('status').textContent='Aplikacja gotowa do działania offline.'}).catch(()=>{})}
